package projecteuler;

import java.util.ArrayList;

public class Problem2 {
//    Each new term in the Fibonacci sequence is generated by
//    adding the previous two terms. By starting with 1 and 2,
//    the first 10 terms will be:
//
//            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//    By considering the terms in the Fibonacci sequence
//    whose values do not exceed four million, find the
//    sum of the even-valued terms.
    static int fib(int n){
        ArrayList<Integer> fib = new ArrayList<>();

        fib.add(1);
        fib.add(2);

        int fibIntN1 = 2;
        int fibIntN2 = 1;
        int fibInt = fibIntN1 + fibIntN2;

        while(fibInt < n){
            fib.add(fibInt);
            fibIntN2 = fibIntN1;
            fibIntN1 = fibInt;
            fibInt = fibIntN1 + fibIntN2;
        }
//        System.out.println(fib);

        int total = 0;
        for(Integer ele : fib){
            if(ele % 2 == 0){
                total += ele;
            }
        }
        return total;
    }
}
